'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="License", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfLicense"),  _
     System.SerializableAttribute()>  _
    Partial Public Class License
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirstNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LicenseExpireField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LicenseIssueField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LicenseNoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LicenseTypeCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LicenseTypeNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Other1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Other2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Other3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RenewNoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StartDateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SurNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TitleNameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmCode() As String
            Get
                Return Me.EmCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmCodeField, value) <> true) Then
                    Me.EmCodeField = value
                    Me.RaisePropertyChanged("EmCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstNameField, value) <> true) Then
                    Me.FirstNameField = value
                    Me.RaisePropertyChanged("FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LicenseExpire() As String
            Get
                Return Me.LicenseExpireField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LicenseExpireField, value) <> true) Then
                    Me.LicenseExpireField = value
                    Me.RaisePropertyChanged("LicenseExpire")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LicenseIssue() As String
            Get
                Return Me.LicenseIssueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LicenseIssueField, value) <> true) Then
                    Me.LicenseIssueField = value
                    Me.RaisePropertyChanged("LicenseIssue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LicenseNo() As String
            Get
                Return Me.LicenseNoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LicenseNoField, value) <> true) Then
                    Me.LicenseNoField = value
                    Me.RaisePropertyChanged("LicenseNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LicenseTypeCode() As String
            Get
                Return Me.LicenseTypeCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LicenseTypeCodeField, value) <> true) Then
                    Me.LicenseTypeCodeField = value
                    Me.RaisePropertyChanged("LicenseTypeCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LicenseTypeName() As String
            Get
                Return Me.LicenseTypeNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LicenseTypeNameField, value) <> true) Then
                    Me.LicenseTypeNameField = value
                    Me.RaisePropertyChanged("LicenseTypeName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Other1() As String
            Get
                Return Me.Other1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Other1Field, value) <> true) Then
                    Me.Other1Field = value
                    Me.RaisePropertyChanged("Other1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Other2() As String
            Get
                Return Me.Other2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Other2Field, value) <> true) Then
                    Me.Other2Field = value
                    Me.RaisePropertyChanged("Other2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Other3() As String
            Get
                Return Me.Other3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Other3Field, value) <> true) Then
                    Me.Other3Field = value
                    Me.RaisePropertyChanged("Other3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RenewNo() As String
            Get
                Return Me.RenewNoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RenewNoField, value) <> true) Then
                    Me.RenewNoField = value
                    Me.RaisePropertyChanged("RenewNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StartDate() As String
            Get
                Return Me.StartDateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StartDateField, value) <> true) Then
                    Me.StartDateField = value
                    Me.RaisePropertyChanged("StartDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SurName() As String
            Get
                Return Me.SurNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SurNameField, value) <> true) Then
                    Me.SurNameField = value
                    Me.RaisePropertyChanged("SurName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TitleName() As String
            Get
                Return Me.TitleNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleNameField, value) <> true) Then
                    Me.TitleNameField = value
                    Me.RaisePropertyChanged("TitleName")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Employee", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfLicense"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Employee
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CC_CODEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DEPARTMENTField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DIVISIONField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_AGEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_BIRTHDATEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_CODEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_COMPANYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_ENAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_ESURNAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_FULLNAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_IDCARDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_MAILField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_MOBILEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_NICKNAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_PICTUREField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_RUNNOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_SEXField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_TNAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_TSURNAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EM_TYPEPICTUREField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EO_EFDATEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EO_EFDATE_MONTHField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EO_EFDATE_YEARField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GROUPField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OP_ENAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OP_TNAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PHONE_OFFICEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PLS_TNAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PO_TNAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SECTERField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SECTIONField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UNITField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CC_CODE() As String
            Get
                Return Me.CC_CODEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CC_CODEField, value) <> true) Then
                    Me.CC_CODEField = value
                    Me.RaisePropertyChanged("CC_CODE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DEPARTMENT() As String
            Get
                Return Me.DEPARTMENTField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DEPARTMENTField, value) <> true) Then
                    Me.DEPARTMENTField = value
                    Me.RaisePropertyChanged("DEPARTMENT")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DIVISION() As String
            Get
                Return Me.DIVISIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DIVISIONField, value) <> true) Then
                    Me.DIVISIONField = value
                    Me.RaisePropertyChanged("DIVISION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_AGE() As String
            Get
                Return Me.EM_AGEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_AGEField, value) <> true) Then
                    Me.EM_AGEField = value
                    Me.RaisePropertyChanged("EM_AGE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_BIRTHDATE() As String
            Get
                Return Me.EM_BIRTHDATEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_BIRTHDATEField, value) <> true) Then
                    Me.EM_BIRTHDATEField = value
                    Me.RaisePropertyChanged("EM_BIRTHDATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_CODE() As String
            Get
                Return Me.EM_CODEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_CODEField, value) <> true) Then
                    Me.EM_CODEField = value
                    Me.RaisePropertyChanged("EM_CODE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_COMPANY() As String
            Get
                Return Me.EM_COMPANYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_COMPANYField, value) <> true) Then
                    Me.EM_COMPANYField = value
                    Me.RaisePropertyChanged("EM_COMPANY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_ENAME() As String
            Get
                Return Me.EM_ENAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_ENAMEField, value) <> true) Then
                    Me.EM_ENAMEField = value
                    Me.RaisePropertyChanged("EM_ENAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_ESURNAME() As String
            Get
                Return Me.EM_ESURNAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_ESURNAMEField, value) <> true) Then
                    Me.EM_ESURNAMEField = value
                    Me.RaisePropertyChanged("EM_ESURNAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_FULLNAME() As String
            Get
                Return Me.EM_FULLNAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_FULLNAMEField, value) <> true) Then
                    Me.EM_FULLNAMEField = value
                    Me.RaisePropertyChanged("EM_FULLNAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_IDCARD() As String
            Get
                Return Me.EM_IDCARDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_IDCARDField, value) <> true) Then
                    Me.EM_IDCARDField = value
                    Me.RaisePropertyChanged("EM_IDCARD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_MAIL() As String
            Get
                Return Me.EM_MAILField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_MAILField, value) <> true) Then
                    Me.EM_MAILField = value
                    Me.RaisePropertyChanged("EM_MAIL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_MOBILE() As String
            Get
                Return Me.EM_MOBILEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_MOBILEField, value) <> true) Then
                    Me.EM_MOBILEField = value
                    Me.RaisePropertyChanged("EM_MOBILE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_NICKNAME() As String
            Get
                Return Me.EM_NICKNAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_NICKNAMEField, value) <> true) Then
                    Me.EM_NICKNAMEField = value
                    Me.RaisePropertyChanged("EM_NICKNAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_PICTURE() As String
            Get
                Return Me.EM_PICTUREField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_PICTUREField, value) <> true) Then
                    Me.EM_PICTUREField = value
                    Me.RaisePropertyChanged("EM_PICTURE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_RUNNO() As String
            Get
                Return Me.EM_RUNNOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_RUNNOField, value) <> true) Then
                    Me.EM_RUNNOField = value
                    Me.RaisePropertyChanged("EM_RUNNO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_SEX() As String
            Get
                Return Me.EM_SEXField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_SEXField, value) <> true) Then
                    Me.EM_SEXField = value
                    Me.RaisePropertyChanged("EM_SEX")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_TNAME() As String
            Get
                Return Me.EM_TNAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_TNAMEField, value) <> true) Then
                    Me.EM_TNAMEField = value
                    Me.RaisePropertyChanged("EM_TNAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_TSURNAME() As String
            Get
                Return Me.EM_TSURNAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_TSURNAMEField, value) <> true) Then
                    Me.EM_TSURNAMEField = value
                    Me.RaisePropertyChanged("EM_TSURNAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EM_TYPEPICTURE() As String
            Get
                Return Me.EM_TYPEPICTUREField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EM_TYPEPICTUREField, value) <> true) Then
                    Me.EM_TYPEPICTUREField = value
                    Me.RaisePropertyChanged("EM_TYPEPICTURE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EO_EFDATE() As String
            Get
                Return Me.EO_EFDATEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EO_EFDATEField, value) <> true) Then
                    Me.EO_EFDATEField = value
                    Me.RaisePropertyChanged("EO_EFDATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EO_EFDATE_MONTH() As String
            Get
                Return Me.EO_EFDATE_MONTHField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EO_EFDATE_MONTHField, value) <> true) Then
                    Me.EO_EFDATE_MONTHField = value
                    Me.RaisePropertyChanged("EO_EFDATE_MONTH")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EO_EFDATE_YEAR() As String
            Get
                Return Me.EO_EFDATE_YEARField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EO_EFDATE_YEARField, value) <> true) Then
                    Me.EO_EFDATE_YEARField = value
                    Me.RaisePropertyChanged("EO_EFDATE_YEAR")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GROUP() As String
            Get
                Return Me.GROUPField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GROUPField, value) <> true) Then
                    Me.GROUPField = value
                    Me.RaisePropertyChanged("GROUP")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OP_ENAME() As String
            Get
                Return Me.OP_ENAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OP_ENAMEField, value) <> true) Then
                    Me.OP_ENAMEField = value
                    Me.RaisePropertyChanged("OP_ENAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OP_TNAME() As String
            Get
                Return Me.OP_TNAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OP_TNAMEField, value) <> true) Then
                    Me.OP_TNAMEField = value
                    Me.RaisePropertyChanged("OP_TNAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PHONE_OFFICE() As String
            Get
                Return Me.PHONE_OFFICEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PHONE_OFFICEField, value) <> true) Then
                    Me.PHONE_OFFICEField = value
                    Me.RaisePropertyChanged("PHONE_OFFICE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PLS_TNAME() As String
            Get
                Return Me.PLS_TNAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PLS_TNAMEField, value) <> true) Then
                    Me.PLS_TNAMEField = value
                    Me.RaisePropertyChanged("PLS_TNAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PO_TNAME() As String
            Get
                Return Me.PO_TNAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PO_TNAMEField, value) <> true) Then
                    Me.PO_TNAMEField = value
                    Me.RaisePropertyChanged("PO_TNAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SECTER() As String
            Get
                Return Me.SECTERField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SECTERField, value) <> true) Then
                    Me.SECTERField = value
                    Me.RaisePropertyChanged("SECTER")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SECTION() As String
            Get
                Return Me.SECTIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SECTIONField, value) <> true) Then
                    Me.SECTIONField = value
                    Me.RaisePropertyChanged("SECTION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UNIT() As String
            Get
                Return Me.UNITField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UNITField, value) <> true) Then
                    Me.UNITField = value
                    Me.RaisePropertyChanged("UNIT")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.ILicenseService")>  _
    Public Interface ILicenseService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILicenseService/WCFLicense", ReplyAction:="http://tempuri.org/ILicenseService/WCFLicenseResponse")>  _
        Function WCFLicense(ByVal emCode As String, ByVal licenseTypeCode As String) As ServiceReference1.License()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILicenseService/WCFLicense", ReplyAction:="http://tempuri.org/ILicenseService/WCFLicenseResponse")>  _
        Function WCFLicenseAsync(ByVal emCode As String, ByVal licenseTypeCode As String) As System.Threading.Tasks.Task(Of ServiceReference1.License())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILicenseService/Test", ReplyAction:="http://tempuri.org/ILicenseService/TestResponse")>  _
        Function Test() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILicenseService/Test", ReplyAction:="http://tempuri.org/ILicenseService/TestResponse")>  _
        Function TestAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILicenseService/GetEmployeeLHBank", ReplyAction:="http://tempuri.org/ILicenseService/GetEmployeeLHBankResponse")>  _
        Function GetEmployeeLHBank() As ServiceReference1.Employee()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILicenseService/GetEmployeeLHBank", ReplyAction:="http://tempuri.org/ILicenseService/GetEmployeeLHBankResponse")>  _
        Function GetEmployeeLHBankAsync() As System.Threading.Tasks.Task(Of ServiceReference1.Employee())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILicenseService/GetEmployeeQuitLHBank", ReplyAction:="http://tempuri.org/ILicenseService/GetEmployeeQuitLHBankResponse")>  _
        Function GetEmployeeQuitLHBank() As ServiceReference1.Employee()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILicenseService/GetEmployeeQuitLHBank", ReplyAction:="http://tempuri.org/ILicenseService/GetEmployeeQuitLHBankResponse")>  _
        Function GetEmployeeQuitLHBankAsync() As System.Threading.Tasks.Task(Of ServiceReference1.Employee())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILicenseService/GetEmployeeLHFG", ReplyAction:="http://tempuri.org/ILicenseService/GetEmployeeLHFGResponse")>  _
        Function GetEmployeeLHFG() As ServiceReference1.Employee()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILicenseService/GetEmployeeLHFG", ReplyAction:="http://tempuri.org/ILicenseService/GetEmployeeLHFGResponse")>  _
        Function GetEmployeeLHFGAsync() As System.Threading.Tasks.Task(Of ServiceReference1.Employee())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILicenseService/GetEmployeeQuitLHFG", ReplyAction:="http://tempuri.org/ILicenseService/GetEmployeeQuitLHFGResponse")>  _
        Function GetEmployeeQuitLHFG() As ServiceReference1.Employee()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILicenseService/GetEmployeeQuitLHFG", ReplyAction:="http://tempuri.org/ILicenseService/GetEmployeeQuitLHFGResponse")>  _
        Function GetEmployeeQuitLHFGAsync() As System.Threading.Tasks.Task(Of ServiceReference1.Employee())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILicenseService/GetEmployeeByEmpCode", ReplyAction:="http://tempuri.org/ILicenseService/GetEmployeeByEmpCodeResponse")>  _
        Function GetEmployeeByEmpCode(ByVal EmpCode As String) As ServiceReference1.Employee()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILicenseService/GetEmployeeByEmpCode", ReplyAction:="http://tempuri.org/ILicenseService/GetEmployeeByEmpCodeResponse")>  _
        Function GetEmployeeByEmpCodeAsync(ByVal EmpCode As String) As System.Threading.Tasks.Task(Of ServiceReference1.Employee())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ILicenseServiceChannel
        Inherits ServiceReference1.ILicenseService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class LicenseServiceClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.ILicenseService)
        Implements ServiceReference1.ILicenseService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function WCFLicense(ByVal emCode As String, ByVal licenseTypeCode As String) As ServiceReference1.License() Implements ServiceReference1.ILicenseService.WCFLicense
            Return MyBase.Channel.WCFLicense(emCode, licenseTypeCode)
        End Function
        
        Public Function WCFLicenseAsync(ByVal emCode As String, ByVal licenseTypeCode As String) As System.Threading.Tasks.Task(Of ServiceReference1.License()) Implements ServiceReference1.ILicenseService.WCFLicenseAsync
            Return MyBase.Channel.WCFLicenseAsync(emCode, licenseTypeCode)
        End Function
        
        Public Function Test() As String Implements ServiceReference1.ILicenseService.Test
            Return MyBase.Channel.Test
        End Function
        
        Public Function TestAsync() As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.ILicenseService.TestAsync
            Return MyBase.Channel.TestAsync
        End Function
        
        Public Function GetEmployeeLHBank() As ServiceReference1.Employee() Implements ServiceReference1.ILicenseService.GetEmployeeLHBank
            Return MyBase.Channel.GetEmployeeLHBank
        End Function
        
        Public Function GetEmployeeLHBankAsync() As System.Threading.Tasks.Task(Of ServiceReference1.Employee()) Implements ServiceReference1.ILicenseService.GetEmployeeLHBankAsync
            Return MyBase.Channel.GetEmployeeLHBankAsync
        End Function
        
        Public Function GetEmployeeQuitLHBank() As ServiceReference1.Employee() Implements ServiceReference1.ILicenseService.GetEmployeeQuitLHBank
            Return MyBase.Channel.GetEmployeeQuitLHBank
        End Function
        
        Public Function GetEmployeeQuitLHBankAsync() As System.Threading.Tasks.Task(Of ServiceReference1.Employee()) Implements ServiceReference1.ILicenseService.GetEmployeeQuitLHBankAsync
            Return MyBase.Channel.GetEmployeeQuitLHBankAsync
        End Function
        
        Public Function GetEmployeeLHFG() As ServiceReference1.Employee() Implements ServiceReference1.ILicenseService.GetEmployeeLHFG
            Return MyBase.Channel.GetEmployeeLHFG
        End Function
        
        Public Function GetEmployeeLHFGAsync() As System.Threading.Tasks.Task(Of ServiceReference1.Employee()) Implements ServiceReference1.ILicenseService.GetEmployeeLHFGAsync
            Return MyBase.Channel.GetEmployeeLHFGAsync
        End Function
        
        Public Function GetEmployeeQuitLHFG() As ServiceReference1.Employee() Implements ServiceReference1.ILicenseService.GetEmployeeQuitLHFG
            Return MyBase.Channel.GetEmployeeQuitLHFG
        End Function
        
        Public Function GetEmployeeQuitLHFGAsync() As System.Threading.Tasks.Task(Of ServiceReference1.Employee()) Implements ServiceReference1.ILicenseService.GetEmployeeQuitLHFGAsync
            Return MyBase.Channel.GetEmployeeQuitLHFGAsync
        End Function
        
        Public Function GetEmployeeByEmpCode(ByVal EmpCode As String) As ServiceReference1.Employee() Implements ServiceReference1.ILicenseService.GetEmployeeByEmpCode
            Return MyBase.Channel.GetEmployeeByEmpCode(EmpCode)
        End Function
        
        Public Function GetEmployeeByEmpCodeAsync(ByVal EmpCode As String) As System.Threading.Tasks.Task(Of ServiceReference1.Employee()) Implements ServiceReference1.ILicenseService.GetEmployeeByEmpCodeAsync
            Return MyBase.Channel.GetEmployeeByEmpCodeAsync(EmpCode)
        End Function
    End Class
End Namespace
