'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Employeeregister
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''body control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents body As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtitle1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtitle1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewbody1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewbody1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewimgEmp21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewimgEmp21 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''previewtxt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtxt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtxt3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtxt4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtxt5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtxt6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tbAttendExpected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAttendExpected As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cbConfrim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbConfrim As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''previewtxt7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btRegister As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btClose As Global.System.Web.UI.WebControls.Button
End Class
