'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class InviteFriendsDetail
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''body control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents body As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtitle4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtitle4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewbody4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewbody4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewdetail4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewdetail4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tbSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btInsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btInsert As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtxt_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lb1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb1 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''div2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtxt_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt_2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lb2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''div3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtxt_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt_3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lb3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb3 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''div4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtxt_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt_4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lb4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb4 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''div5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtxt_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt_5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lb5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb5 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''div6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtxt_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt_6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lb6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb6 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''div7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtxt_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt_7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lb7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb7 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''div8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtxt_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt_8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lb8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb8 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''div9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div9 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtxt_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt_9 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lb9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb9 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''div10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''previewtxt_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt_10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lb10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb10 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''previewtxt17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewtxt17 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMsg As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btSendMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSendMail As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btClose As Global.System.Web.UI.WebControls.Button
End Class
