'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProjectNew
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''hdnSelectedTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectedTab As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lbTab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTab1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbTab2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTab2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbTab3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTab3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbTab4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTab4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbTab5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTab5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbTab6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTab6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbProjectName_tab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbProjectName_tab1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbDateFr_tab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDateFr_tab1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbDateTo_tab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDateTo_tab1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbSubjectMail_tab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSubjectMail_tab1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbFontName_tab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFontName_tab1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbColor_tab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbColor_tab1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbURL As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rdActiveFlag_tab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdActiveFlag_tab1 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''tbBackgroud_tab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBackgroud_tab1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''FileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbPicture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPicture As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hfFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFileName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btTmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btTmp As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hfIdTab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdTab1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''tbBackgroud_tab2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBackgroud_tab2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbFontColor_tab2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFontColor_tab2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hfIdTab2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdTab2 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''tbBackgroud_tab3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBackgroud_tab3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbFontColor_tab3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFontColor_tab3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''FileUpload3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload3 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbPicture3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPicture3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hfFileName3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFileName3 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btTmp2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btTmp2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''tbTextMessage_tab3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTextMessage_tab3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbTextFontName_tab3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTextFontName_tab3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbTextFontColor_tab3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTextFontColor_tab3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hfIdTab3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdTab3 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''tbBackgroud_tab4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBackgroud_tab4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''FileUpload4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload4 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbPicture4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPicture4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hfFileName4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFileName4 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btTmp3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btTmp3 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''tbTextMessage_tab4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTextMessage_tab4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbTextFontName_tab4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTextFontName_tab4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbTextFontColor_tab4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTextFontColor_tab4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hfIdTab4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdTab4 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''tbBackgroud_tab5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBackgroud_tab5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbFontColor_tab5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFontColor_tab5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hfIdTab5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdTab5 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''tbBackgroud_tab6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBackgroud_tab6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbFontColor_tab6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFontColor_tab6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbTextMessage_tab6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTextMessage_tab6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbTextFontName_tab6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTextFontName_tab6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hfIdTab6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdTab6 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btInsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btInsert As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hfIdTab7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdTab7 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cbConfrim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbConfrim As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''TextBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hfProjectId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfProjectId As Global.System.Web.UI.WebControls.HiddenField
End Class
